### ISSUE TITLE
Mismatch in failed tests count

### ISSUE THREAD

**Issue by vkrol** [winterbe/jest-teamcity-reporter#12]
Hello!

I have the following failing test:
```
describe("test suite", () => {
	it("test", () => {
		expect(1).toEqual(2);
	});
});
```
But TeamCity thinks that this is two tests: https://goo.gl/KxR5De
I use TeamCity 10.0.4 and Jest 19.0.0.

**Comment by vkrol** [comment]
Maybe these lines of code are redundant https://github.com/winterbe/jest-teamcity-reporter/blob/master/index.js#L23-L27 What do you think about it?

**Comment by vkrol** [comment]
If I comment out these lines than the failed tests count is correct.

**Comment by winterbe** [comment]
Thanks. I'll fix this next week.

Veniamin Krol <notifications@github.com> schrieb am Sa. 1. Apr. 2017 um
15:34:

**Comment by vkrol** [comment]
@winterbe thanks! I can create the PR with the removing of these lines of code if you think that this is correct.

**Comment by vkrol** [comment]
@winterbe thanks!
