### ISSUE TITLE
jest --coverage support

### ISSUE THREAD

**Issue by ghost** [winterbe/jest-teamcity-reporter#14]

**Comment by winterbe** [comment]
Jest coverage creates a HTML report in the project directory. I'm not
entirely sure but iirc you can create custom report tabs in teamcity build
configs to show that page.

Igor Pelekhan <notifications@github.com> schrieb am Do. 29. Juni 2017 um
12:09:

**Comment by isakb** [comment]
The HTML report is good for detailed analysis, but some other Teamcity reporters support generating coverage in a format that TeamCity understands, which is useful to have similar views in TeamCity:

![image](https://user-images.githubusercontent.com/404593/27964919-37d98f06-633a-11e7-9786-1cdf891dd286.png)

![image](https://user-images.githubusercontent.com/404593/27965037-a1d1e282-633a-11e7-92b0-95643164c1fd.png)

It would be awesome to have this built-in to this reporter too.

**Comment by isakb** [comment]
Here is an example of how such a reporter can look for mocha: https://github.com/iageengineering/nodejs-mocha-teamcity-reporter/blob/master/index.js

**Comment by ipelekhan** [comment]
I think I should close the issue, found that you can use any Istanbul reporters via [coverageReporters](https://facebook.github.io/jest/docs/configuration.html#coveragereporters-array-string) property, and it's possible to use [teamcity reporter](https://github.com/gotwarlost/istanbul/tree/master/lib/report). Seems like it may be outdated, but it works for me.

**Comment by isakb** [comment]
Thanks @ipelekhan, I also totally missed that until you pointed it out. It works for me too.

**Comment by an83** [comment]
Found this link helpful in setting up front-end coverage in teamcity 
https://blog.jetbrains.com/teamcity/2017/08/build-react-apps-with-teamcity/
![coverage](https://user-images.githubusercontent.com/853513/36003536-a00060e4-0d82-11e8-9854-f907242d8eea.PNG)
