### ISSUE TITLE
Usage of title instead of fullName for test case results

### ISSUE THREAD

**Issue by m-malkowski** [winterbe/jest-teamcity-reporter#23]
Hey, 

I've noticed in our CI that number of tests reported by TeamCity is different than number of tests reported when running them on your local, and the reason is I believe that TC is overriding the results for duplicated names of the tests?

So if there are 2 tests suites:
```js
describe('Component A', () => {
  describe('in default variant', () => {
    it('renders correctly', () => {})
  });
  describe('in complex variant', () => {
    it('renders correctly', () => {})
  })
});
```
Local run will report 2 tests, while for TeamCity it seems to be picked up as 1 test (as the name being used is `renders correctly` without the describe prefixes.

This issue could be solved if we would start using `fullName` instead of current `title` field from testResult.

Any thoughts @winterbe ? I Could create a PR if that's a correct way of addressing this issue

**Comment by lukebarton** [comment]
I think you just need to upgrade your version of `jest-teamcity-reporter` because:

https://github.com/winterbe/jest-teamcity-reporter/blob/master/index.js#L34

**Comment by winterbe** [comment]
This is right. I close this issue due to inactivity.
