### ISSUE TITLE
Adding non empty validation for process.env.TEAMCITY_VERSION 

### ISSUE THREAD

**Issue by ynahmany** [winterbe/jest-teamcity-reporter#24]
Hi, 
I am using Docker and passing TEAMCITY_VERSION env variable in either way(empty or not). 
I would like the package to check if it is empty or not and not only existing of it. 

  I tried to push my changes and open pull request but got 403 with permissions error.

Can you help ?

**Comment by winterbe** [comment]
You cannot push to foreign repositories on GitHub. You have to fork the repository to you own account, then push the changes to your fork and create a pull request.

However I don't see the benefit of the described change. This might be a breaking change to others who have set the environment variable to an empty value.

**Comment by ynahmany** [comment]
Got it. 
Thanks!
