### ISSUE TITLE
Suggestion: rename to jest-teamcity-results-processor

### ISSUE THREAD

**Issue by ToshB** [winterbe/jest-teamcity-reporter#5]
I think the name is a bit misleading, as jest does not support custom reporters at this time. But we're getting closer: https://github.com/facebook/jest/pull/2115

And also, a reporter would report progress to teamcity as the tests are running, while this reports nothing until the test run is complete, which is not optimal if there are a lot of tests.

**Comment by winterbe** [comment]
Hm, I don't see where the name `reporter` is misleading here. The term is chosen from the context of Teamcity (not Jest) where the used technique is called `Reporting Messages`, see [TC docs](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-reportingMessagesForBuildLogReportingMessagesForBuildLog).

I appreciate your feedback, however I don't want to change the name of this project. But I'm happy to switch the implementation from `resultsProcessor` to something better suitable when available (or accept PRs).

**Comment by ccarpita** [comment]
Now that `reporters` is a configuration option, the name is misleading to anyone familiar with the Jest 20+ API  (which is now the previous major version).  One would expect to be able to drop this module name into the `reporters` configuration list, when in fact it is a test-results-processor.   

Following the principle of least surprise, the best thing IMHO would be to split this into two modules, supporting both APIs:

* `jest-teamcity-reporter`
* `jest-teamcity-results-processor`

And bump the major version.  That way you can retain your npm name, while clearly communicating a breaking change.

I have a backlog ticket for this, but don't want to duplicate work, if you're planning on making this kind of change.   If not, I'll fork internally :)
