### ISSUE TITLE
When this is used with jest 18.0.0 the exit code is 0 instead of 1 with failed tests.

### ISSUE THREAD

**Issue by sontek** [winterbe/jest-teamcity-reporter#6]
I originally reported here before I realized it was this plugin that made it not work:

https://github.com/facebook/jest/issues/2470

Any ideas why?

**Comment by dagstuan** [comment]
@sontek: Jest 18 had a breaking change where "the testResultsProcessor function is now required to return the modified results". This made the plugin fail. The author seems to have fixed it on github, but still haven't released an updated npm package. In the meantime I updated my `package.json` to fetch from github instead, such as this: `"jest-teamcity-reporter": "git://github.com/winterbe/jest-teamcity-reporter.git"`

**Comment by winterbe** [comment]
Happy new year. I've published version 0.3.0. This should fix the issue.
