### ISSUE TITLE
is --teamcity necessary?

### ISSUE THREAD

**Issue by pitermarx** [winterbe/jest-teamcity-reporter#7]
from this line https://github.com/winterbe/jest-teamcity-reporter/blob/master/index.js#L3
i read that the reporter is called if the env var is set, even if the --teamcity flag is not set.

This could be specified in the docs

**Comment by blainekasten** [comment]
I removed the teamcity flag and it still running fine.

**Comment by winterbe** [comment]
This has been added by @snypelife. --teamcity flag is no longer necessary if the env variable is set. 

See: https://github.com/winterbe/jest-teamcity-reporter/pull/3

I've updated the README accordingly.
